---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dijsutpm/public_html/
    - /bin/cp -R .vscode $DEPLOYPATH
    - /bin/cp -R dist $DEPLOYPATH
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    /bin/cp -R tailwind.config.js $DEPLOYPATH
    /bin/cp -R tsconfig.json $DEPLOYPATH
    /bin/cp -R astro.config.mjs $DEPLOYPATH